version: '3.9'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf